language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install pycparser==2.18; pip install unittest2; fi
  - pip install -r requirements.txt
  - pip install coveralls
script: nosetests -s -v --with-coverage --cover-package=inotify
after_success:
  - coveralls
