language: python
matrix:
    include:
        - os: linux
          dist: precise
          python: 2.6
          cache: pip
        - os: linux
          dist: xenial
          python: 2.7
        - os: linux
          dist: precise
          python: 3.3
        - os: linux
          dist: trusty
          python: 3.4
        - os: linux
          dist: xenial
          python: 3.5
        - os: linux
          dist: xenial
          python: 3.6
        - os: linux
          dist: xenial
          python: 3.7
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install pycparser==2.18 idna==2.7; pip install unittest2; fi
  - pip install -r requirements.txt
  - pip install coveralls
script: nosetests -s -v --with-coverage --cover-package=inotify
after_success:
  - coveralls
